# Generated by Django 6.0.1 on 2026-01-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('position', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('division', models.CharField(max_length=30)),
                ('staffID', models.CharField(max_length=7, unique=True)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['staffID'],
            },
        ),
    ]
